### ISSUE TITLE
截断(truncate)样式不生效

### ISSUE THREAD

**Issue by 981377660LMT** [981377660LMT/ts#406]

**Comment by 981377660LMT** [comment]
<img width="855" alt="image" src="https://github.com/981377660LMT/ts/assets/45849137/06fed505-cf0b-4d96-b960-c904c2d7541e">
```css
.column-sortable-list-item .text {
    width: 90px;
    text-overflow: ellipsis;
    overflow: hidden;
    margin-right: 8px;
    white-space: nowrap;
    margin-left: 4px;
}
```

**Comment by 981377660LMT** [comment]
触发条件：
1. 一定的宽度
2. truncate 类

```less
.truncate {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```

**Comment by 981377660LMT** [comment]
```less
       .mtd-button-label {
          overflow: hidden;
          white-space: nowrap;
          text-overflow: ellipsis;
          display: flex;
          align-items: center;
        }
```

为什么没有省略号？
因为用了flex布局。

**Comment by 981377660LMT** [comment]
如果你想在使用 flex 布局的同时，也能显示省略号，可以尝试以下方法：

1. 在 `.mtd-button-label` 中添加一个子元素，例如 `<span>`，并将文本放在这个 `<span>` 中。

2. 将 `overflow: hidden;`，`white-space: nowrap;` 和 `text-overflow: ellipsis;` 这三个属性应用到这个 `<span>` 上，而不是应用到 `.mtd-button-label` 上。

3. 给这个 `<span>` 设置 `min-width: 0;`。

以下是一个示例：

```css
.mtd-button-label {
  display: flex;
  align-items: center;
}

.mtd-button-label span {
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
  min-width: 0;
}
```

然后在 HTML 中这样使用：

```html
<div class="mtd-button-label">
  <span>这里是一段很长的文本，可能会超出容器宽度</span>
</div>
```

这样，当文本长度超出 `.mtd-button-label` 的宽度时，就会在 `<span>` 中显示省略号。
