### ISSUE TITLE
一个flex容器只对其直接子元素生效

### ISSUE THREAD

**Issue by 981377660LMT** [981377660LMT/ts#407]

**Comment by 981377660LMT** [comment]
一个flex容器只对其直接子元素生效。也就是说，flex布局的属性（如justify-content, align-items, flex-direction等）只会影响直接的子元素，而不会影响子元素的子元素（即孙子元素）。

例如，下面的代码创建了一个flex容器（.parent），并设置了justify-content: center：
```css
.parent {
  display: flex;
  justify-content: center;
}
```
在这个例子中，.parent的直接子元素会被居中对齐，但是这个居中对齐的效果不会传递给子元素的子元素。如果你想让子元素的子元素也居中对齐，你需要给子元素也设置display: flex和justify-content: center：
```css
.child {
  display: flex;
  justify-content: center;
}
```
这样，.child的子元素也会被居中对齐。
