### ISSUE TITLE
textArea 自动调节高度

### ISSUE THREAD

**Issue by 981377660LMT** [981377660LMT/ts#434]
```ts
  useEffect(() => {
    const textarea = textAreaRef.current;
    if (textarea) {
      textarea.style.height = 'auto';
      textarea.style.height = `${textarea.scrollHeight}px`;
    }
  }, [textAreaRef?.current?.value]);
```

**Comment by 981377660LMT** [comment]
去除 textArea 样式

如果你想要去除 `textarea` 的默认样式，你可以使用 CSS 来实现。以下是一个基本的例子：

```css
textarea {
  outline: none;
  border: none;
  background: none;
  resize: none;
}
```

这段 CSS 代码将移除 `textarea` 的轮廓（`outline`）、边框（`border`）、背景（`background`）以及禁止用户调整大小（`resize`）。你可以根据需要添加或删除属性。
