### ISSUE TITLE
修改 scrollbar 样式

### ISSUE THREAD

**Issue by 981377660LMT** [981377660LMT/ts#446]

**Comment by 981377660LMT** [comment]
![image](https://github.com/981377660LMT/ts/assets/45849137/b03f29f8-53a6-4c26-92ca-0234ea0bcd52)

**Comment by 981377660LMT** [comment]
https://www.digitalocean.com/community/tutorials/customize-the-browsers-scrollbar-with-css

**Comment by 981377660LMT** [comment]
```less
/* Designing for scroll-bar */
&::-webkit-scrollbar {
  width: 6px;
}

/* Track */
&::-webkit-scrollbar-track {
  background: gainsboro;
  border-radius: 5px;
}

/* Handle */
&::-webkit-scrollbar-thumb {
  background: black;
  border-radius: 5px;
}

/* Handle on hover */
&::-webkit-scrollbar-thumb:hover {
  background: #555;
}
```
