### ISSUE TITLE
文本换行

### ISSUE THREAD

**Issue by 981377660LMT** [981377660LMT/ts#449]
1. 单行文本溢出显示省略号
如果你想让单行文本在溢出时显示省略号，你可以使用以下CSS样式：

```css
div {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

这里的`white-space: nowrap;`保证文本在一行内显示，`overflow: hidden;`用于隐藏超出div的文本，`text-overflow: ellipsis;`则是在文本溢出时显示省略号。

这样，当div内的文本长度超过其宽度时，超出的部分就会被替换为省略号。

2. 多行文本溢出显示省略号
如果你想让多行文本在溢出时显示省略号，你可以使用以下CSS样式：

```css
div {
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: N; /* 'N' 是你想显示的行数 */
  overflow: hidden;
}
```

这种方法使用了WebKit的非标准CSS属性，因此只在WebKit浏览器（如Chrome和Safari）中有效。`-webkit-line-clamp`属性用于限制在一个块元素显示的文本的行数。`N`是你想要显示的文本的行数。超出这个行数的文本会被截断并显示省略号。

注意，这种方法不是标准的CSS，可能在非WebKit浏览器中无效。
