### ISSUE TITLE
font-weight

### ISSUE THREAD

**Issue by 981377660LMT** [981377660LMT/ts#698]
# 详细介绍 `font-weight`

`font-weight` 是 CSS（层叠样式表）中用于设置字体粗细的属性。通过调整字体的粗细，可以增强文本的可读性、强调特定内容或实现设计中的视觉层次感。本文将全面介绍 `font-weight` 的用法、可选值、兼容性以及在实际开发中的应用技巧。

## 一、`font-weight` 的定义

`font-weight` 属性用于指定字体的粗细程度。它可以接受关键字（例如 `normal`、`bold`）或数值（例如 `400`、`700`），以灵活控制字体的显示效果。

```css
/* 使用关键字 */
p {
    font-weight: bold;
}

/* 使用数值 */
h1 {
    font-weight: 700;
}
```

### 1. 关键字值

- **`normal`**
  
  默认值，表示正常的字体粗细。通常对应数值 `400`。

  ```css
  .normal-text {
      font-weight: normal;
  }
  ```

- **`bold`**
  
  表示加粗的字体。通常对应数值 `700`。

  ```css
  .bold-text {
      font-weight: bold;
  }
  ```

- **`bolder`**
  
  相对于父元素的字体粗细，选择更粗的级别。

  ```css
  .bolder-text {
      font-weight: bolder;
  }
  ```

- **`lighter`**
  
  相对于父元素的字体粗细，选择更细的级别。

  ```css
  .lighter-text {
      font-weight: lighter;
  }
  ```

### 2. 数值值

`font-weight` 也可以接受数值值，范围为 `100` 到 `900`，步长为 `100`。这些数值提供了更细粒度的控制，与字体家族中定义的粗细程度相对应。

- **常用数值对应关系：**

  | 数值 | 描述       |
  |------|------------|
  | 100  | 极细       |
  | 200  | 纤细       |
  | 300  | 细         |
  | 400  | 正常（等同于 `normal`） |
  | 500  | 中等       |
  | 600  | 半粗       |
  | 700  | 粗（等同于 `bold`） |
  | 800  | 超粗       |
  | 900  | 极粗       |

  ```css
  .light-text {
      font-weight: 300;
  }

  .medium-text {
      font-weight: 500;
  }

  .heavy-text {
      font-weight: 900;
  }
  ```

### 3. 全局默认值

- **`inherit`**
  
  继承父元素的 `font-weight` 值。

  ```css
  .inherited-text {
      font-weight: inherit;
  }
  ```

- **`initial`**
  
  将 `font-weight` 设置为其默认值 `normal`。

  ```css
  .initial-text {
      font-weight: initial;
  }
  ```

- **`unset`**
  
  如果继承层次中的一个是继承，则等同于 `inherit`，否则等同于 `initial`。

  ```css
  .unset-text {
      font-weight: unset;
  }
  ```

### 1. 字体权重的可用性

不同的字体家族（font family）提供的字体粗细级别可能不同。在某些字体家族中，所有权重级别都可用，而在其他字体家族中，可能只有部分权重级别可用。例如，某些字体可能仅提供 `normal` 和 `bold` 两种粗细，而缺乏中等或超粗等级别。

### 2. 合成字体粗细

当指定的 `font-weight` 值在字体家族中不可用时，浏览器会尽量合成一个接近的粗细。例如，如果某字体家族仅提供 `400` 和 `700` 两种粗细，当指定 `500` 时，浏览器可能会选择 `400` 作为最接近的值。

### 3. 变量字体（Variable Fonts）

变量字体允许在一个字体文件中定义多个粗细级别，实现更加灵活和精确的字体粗细控制。对于支持变量字体的字体家族，可以通过 `font-weight` 精确设置所需的粗细。

```css
.variable-text {
    font-family: 'YourVariableFont', sans-serif;
    font-weight: 550; /* 支持变量字体时，可以更精确地设置粗细 */
}
```

## 四、`font-weight` 的兼容性

`font-weight` 属性在现代浏览器中广泛支持，包括：

- **桌面浏览器：** Chrome, Firefox, Safari, Edge, Opera
- **移动浏览器：** iOS Safari, Android 浏览器, Chrome for Android

然而，旧版浏览器（如 IE 8 及更早版本）对某些数值级别的支持可能不完全。因此，在开发时应考虑目标用户群体的浏览器使用情况，并根据需要进行兼容性处理。

### 1. 使用语义化的粗细

- **强调文本：** 使用 `bold` 或较高的数值（如 `700`）来强调重要信息。
- **次要文本：** 使用较低的数值（如 `300`）来显示次要信息或辅助说明。
- **一致性：** 确保整个项目中 `font-weight` 的使用保持一致，避免混乱的视觉效果。

### 2. 与其他字体属性配合使用

- **`font-style`：** 例如，斜体（`italic`）与粗体（`bold`）的结合，可以实现丰富的文本表现。
  
  ```css
  .bold-italic-text {
      font-weight: bold;
      font-style: italic;
  }
  ```

- **`line-height`：** 调整行高以搭配不同粗细的字体，确保文本的可读性和视觉美观。
  
  ```css
  .styled-text {
      font-weight: 600;
      line-height: 1.5;
  }
  ```

### 3. 响应式设计中的字体粗细

在响应式设计中，可能需要根据屏幕尺寸调整字体的粗细，以适应不同设备的显示需求。

```css
/* 大屏设备 */
@media (min-width: 1024px) {
    .responsive-text {
        font-weight: 700;
    }
}

/* 小屏设备 */
@media (max-width: 1023px) {
    .responsive-text {
        font-weight: 500;
    }
}
```

### 4. 避免过度使用粗体

过度使用 `bold` 或较高数值的 `font-weight` 可能导致视觉疲劳。合理分配粗体的使用，确保重点突出而不显得杂乱。

## 六、示例代码

以下是一个综合示例，展示了如何在 Vue 组件中使用 `font-weight` 属性来控制文本的粗细：

```vue
<template>
    <div class="text-container">
        <p class="regular-text">这是一段普通文本。</p>
        <p class="bold-text">这是一段加粗文本。</p>
        <p class="light-text">这是一段纤细文本。</p>
        <p class="dynamic-text" :style="{ fontWeight: isBold ? '700' : '300' }">
            这是一段动态切换粗细的文本。
        </p>
    </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
    setup() {
        const isBold = ref(false);

        const toggleBold = () => {
            isBold.value = !isBold.value;
        };

        return {
            isBold,
            toggleBold,
        };
    },
});
</script>

<style scoped>
.regular-text {
    font-weight: normal; /* 等同于 400 */
}

.bold-text {
    font-weight: bold; /* 等同于 700 */
}

.light-text {
    font-weight: 300;
}

.text-container p {
    margin: 10px 0;
}

.dynamic-text {
    cursor: pointer;
}

.dynamic-text:hover {
    text-decoration: underline;
}
</style>
```

### 解释：

- **静态设置：**
  
  - `.regular-text` 使用 `font-weight: normal` 显示正常粗细的文本。
  - `.bold-text` 使用 `font-weight: bold` 显示加粗文本。
  - `.light-text` 使用数值 `font-weight: 300` 显示纤细文本。

- **动态设置：**
  
  - `.dynamic-text` 的 `font-weight` 根据 `isBold` 的值动态切换，在模板中通过内联样式绑定实现。

### 1. 问：`font-weight` 的数值为什么是 `100` 到 `900`？

答：`font-weight` 的数值表示字体的粗细级别，范围从 `100`（极细）到 `900`（极粗），步长为 `100`。这种设计允许开发者以更细粒度控制字体的显示效果。数值越大，字体越粗。

### 2. 问：如果字体家族不支持指定的 `font-weight`，浏览器会如何处理？

答：如果字体家族不支持指定的 `font-weight` 值，浏览器会尽量选择最接近的可用粗细。如果指定的 `font-weight` 比字体家族中最粗的还要粗，浏览器会选择最粗的可用值；反之亦然。

### 3. 问：如何确保自定义字体支持多种 `font-weight`？

答：选择支持多种粗细级别的字体家族，或使用变量字体（Variable Fonts），它们允许在单一字体文件中定义多个粗细级别。同时，在 `@font-face` 规则中正确设置不同的 `font-weight`，以确保浏览器能够识别并加载相应的字体文件。

```css
@font-face {
    font-family: 'CustomFont';
    src: url('/fonts/CustomFont-Regular.woff2') format('woff2');
    font-weight: 400;
}

@font-face {
    font-family: 'CustomFont';
    src: url('/fonts/CustomFont-Bold.woff2') format('woff2');
    font-weight: 700;
}
```

### 4. 问：如何在 Tailwind CSS 中使用 `font-weight`？

答：Tailwind CSS 提供了一系列的实用类，用于快速设置文本的粗细。

```html
<p class="font-normal">正常文本</p>
<p class="font-bold">加粗文本</p>
<p class="font-light">纤细文本</p>
<p class="font-medium">中等粗细文本</p>
```

### 5. 问：`font-weight` 如何影响字体的渲染性能？

答：较高的 `font-weight` 可能需要加载更多的字体文件，尤其在使用自定义字体时。此外，频繁切换字体粗细可能会影响渲染性能。因此，建议合理规划和优化字体加载，避免不必要的字体切换，以提升页面加载和渲染效率。

## 八、总结

`font-weight` 是一个强大的 CSS 属性，通过控制文本的粗细，可以显著影响网页的视觉效果和可读性。理解其工作原理、可选值及与字体家族的关系，有助于开发者在设计中做出更明智的决策。合理使用 `font-weight`，结合其他字体属性，可以创建出既美观又高效的文本显示效果。

在实际开发中，应根据具体需求选择合适的字体粗细，确保内容清晰、层次分明，同时注意性能优化和跨浏览器兼容性。
